baseURL = "https://ke.shoogle.net/kenya"
languageCode = "en"
title = "Kenya"
theme = "ln-base"

disableKinds = ["RSS", "robotsTXT"]
enableGitInfo = true

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]

[params]
  site = "Shoogle"
  org = "lokal-ninja"
  repo = "kenya"

[taxonomies]
  shop = "shops"

